### ISSUE TITLE
Connection Refused when accessing web ui

### ISSUE THREAD

**Issue by zeighy** [sipeed/NanoKVM#160]
I'm getting a connection refused when trying to access the web ui on a browser. I can ping ok. can ssh to the device. Tried switching from http to https (and generating self-signed certs) but it just says connection refused.

Tried to disabled tailscale in case it was interfering, nope. Tried on a different network, nope. Access via tailscale, nope. Somehow the webserver just isn't responding or refusing. But ping and ssh continues to work either way (local or tailscale ip).

**Comment by nwgat** [comment]
Firmware Version?

**Comment by zeighy** [comment]
> Firmware Version?

Is there a way to find that? I couldn't remember, but it was whatever came with the card that was shipped with the full nanokvm. I haven't flashed to update, other than maybe use the webui to update in early November.

**Comment by seppo81** [comment]
I have the same issue. I could update the firmware after  some problems under 1.2.1. But with the newer 1.3, I could not get the webUI. With 1.2.1 I could login in the webui.

**Comment by brycesweaver** [comment]
Experiencing the same issue.

**Comment by ggee** [comment]
Thanks for the workaround.  Got my Lite and was a painful start. Didn't know I needed to supply and SD card, just saw it boot looping.  Once I found out I needed a card, I installed latest and got this issue.  Still don't understand the different versions.  After installing 1.2.1, I opened UI and it wanted to upgrade from 1.0 to 2.1.

**Comment by ggee** [comment]
Thanks for the workaround.  Got my Lite and was a painful start. Didn't know I needed to supply and SD card, just saw it boot looping.  Once I found out I needed a card, I installed latest and got this issue.  Still don't understand the different versions.  After installing 1.2.1, I opened UI and it wanted to upgrade from 1.0 to 2.1.

**Comment by rursache** [comment]
same issue, had to flash 1.2.1

**Comment by zeighy** [comment]
So, I got my other nanoKVM back that didn't have issues. Was on loan to a buddy. Confirmed no update was put on it since on loan, it's running:
Image Version
2024-08-17-18-13-713161.img
Application Version
2.0.9

My best assumption is that the problematic one has the same exact since I received and configured identically, other than have a different hostname.

Anyway, second device seems to be running fine. The first one I reported with issues still had the problem. So, now that I had some comparison, I took the sdcard out and attempted to flash 1.3.0 but for some reason both Belana Etcher and Rufus would not read the image file downloaded from github. Flashed 1.2.1 (which appears to be the same version already on both devices).

First device booted no issue. I'm still not sure what's up with that but reflashing 1.2.1 seems to fix it. Based on this thread, seems like similar outcomes from other people. It did update the webapp to 2.1.1 (was 1.0.0 on fresh flash). I'm keeping the second device on webapp 2.0.9 for now.

**Comment by duffysk** [comment]
Having the same issue since update attempted today.

**Comment by duffysk** [comment]
Having the same issue after updating to 1.3.0.

**Comment by Krusenbaum** [comment]
I have the same issue on a brand new device (PCIe version).

**Comment by Fuxiz** [comment]
Im looking at the issue right now and I get these logs when trying to start the service. 
`# /etc/init.d/S95nanokvm start 
beta
# load config success
-- [E] write failed
oled not exist
ping: usage error: Destination address required
192.168.1.33
stop service...
OK
start update......
create temporary directory /root/.kvm-cache/
download firmware...
download from https://cdn.sipeed.com/nanokvm/latest.zip?n=1744196295
download firmware done
download lib...
update failed
download lib failed, content_type: application/json; charset=utf-8
killall: kvm_system: no process killed
killall: NanoKVM-Server: no process killed
rm: can't remove '/tmp/kvm_system': No such file or directory
rm: can't remove '/tmp/server': No such file or directory
beta
OK
load config success
-- [E] write failed
oled not exist
ping: usage error: Destination address required
192.168.1.33
stop service...
OK
start update......
create temporary directory /root/.kvm-cache/
download firmware...
download from https://cdn.sipeed.com/nanokvm/latest.zip?n=1744196367
download firmware done
download lib...
update failed
download lib failed, content_type: application/json; charset=utf-8
killall: kvm_system: no process killed
killall: NanoKVM-Server: no process killed
rm: can't remove '/tmp/kvm_system': No such file or directory
rm: can't remove '/tmp/server': No such file or directory
beta
OK
-- [E] write failed
oled not exist



# update failed
[Errno 2] No such file or directory: '/root/.kvm-cache//latest.zip'
Traceback (most recent call last):
  File "/kvmapp/system/update-nanokvm.py", line 126, in <module>
    main()
  File "/kvmapp/system/update-nanokvm.py", line 121, in main
    shutil.rmtree(temporary)
  File "/usr/lib/python3.11/shutil.py", line 722, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.11/shutil.py", line 720, in rmtree
    orig_st = os.lstat(path, dir_fd=dir_fd)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.kvm-cache/'
`
I tried and fixed the temporary variable `temporary = "/root/.kvm-cache" ` but I still get download problems 
Trying wget `wget --header="token: MaixVision2024" "https://maixvision.sipeed.com/api/v1/nanokvm/encryption?uid=$(cat /device_key)"`
I get wget: not an http or ftp url:

**Comment by grostim** [comment]
I have the same issue (web server not running), but a different log:

```
# /etc/init.d/S95nanokvm stop
killall: kvm_system: no process killed
killall: NanoKVM-Server: no process killed
rm: can't remove '/tmp/kvm_system': No such file or directory
rm: can't remove '/tmp/server': No such file or directory
OK
# /etc/init.d/S95nanokvm start
beta
# [SAMPLE_COMM_SNS_ParseIni]-2204: Parse /mnt/data/sensor_cfg.ini
[parse_source_devnum]-1797: devNum =  1
[parse_sensor_name]-1878: sensor =  LONTIUM_LT6911_2M_60FPS_8BIT
[parse_sensor_busid]-1907: bus_id =  4
[parse_sensor_i2caddr]-1918: sns_i2c_addr =  ff
[parse_sensor_mipidev]-1929: mipi_dev =  0
[parse_sensor_laneid]-1940: Lane_id =  2, 4, 3, 1, 0
[parse_sensor_pnswap]-1951: pn_swap =  0, 0, 0, 0, 0
[parse_sensor_mclken]-1973: mclk_en =  0
[parse_sensor_mclk]-1984: mclk =  0
try release sys ok
mmf insmod..
rmmod: can't unload module 'soph_vpss': Resource temporarily unavailable
insmod: can't insert '/mnt/system/ko/soph_base.ko': File exists
insmod: can't insert '/mnt/system/ko/soph_rtos_cmdqu.ko': File exists
-- [E] write failed
oled not exist
insmod: can't insert '/mnt/system/ko/soph_fast_image.ko': File exists
rm: can't remove '/etc/kvm/oled_exist': No such file or directory
insmod: can't insert '/mnt/system/ko/soph_mipi_rx.ko': File exists
insmod: can't insert '/mnt/system/ko/soph_snsr_i2c.ko': File exists
192.168.1.105
insmod: can't insert '/mnt/system/ko/soph_vi.ko': File exists
rm: can't remove '/etc/kvm/wifi_exist': No such file or directory
insmod: can't insert '/mnt/system/ko/soph_vpss.ko': File exists
[_mmf_init]-871: maix multi-media version:67a90e2-musl_riscv64
[SAMPLE_COMM_SNS_ParseIni]-2204: Parse /mnt/data/sensor_cfg.ini
[parse_source_devnum]-1797: devNum =  1
[parse_sensor_name]-1878: sensor =  LONTIUM_LT6911_2M_60FPS_8BIT
[parse_sensor_busid]-1907: bus_id =  4
[parse_sensor_i2caddr]-1918: sns_i2c_addr =  ff
[parse_sensor_mipidev]-1929: mipi_dev =  0
[parse_sensor_laneid]-1940: Lane_id =  2, 4, 3, 1, 0
[parse_sensor_pnswap]-1951: pn_swap =  0, 0, 0, 0, 0
[parse_sensor_mclken]-1973: mclk_en =  0
[parse_sensor_mclk]-1984: mclk =  0
pstSize->u32Width = 1920
pstSize->u32Height = 1080
[ION] 12533760  8b300000  VbPool0
[ION] 294912  8bef4000  ISP_SHARED_BUFFER_0
alloc_buf_size(294912): 294912, phy_addr(8bef4000): 0x8bef4000, buffer_name: ISP_SHARED_BUFFER_0
ion_data.size:294912, ion_data.addr_p:0x8bef4000, ion_data.name:ISP_SHARED_BUFFER_0
pstSize->u32Width = 1920
pstSize->u32Height = 1080
pstSize->u32Width = 1920
pstSize->u32Height = 1080
ISP Vipipe(0) Allocate pa(0x8bef4000) va(0x0x3fcdaaa000) size(291424)
pstSize->u32Width = 1920
pstSize->u32Height = 1080
stSnsrMode.u16Width 1920 stSnsrMode.u16Height 1080 60.000000 wdrMode 0 pstSnsObj 0x3fce828e20
pstSize->u32Width = 1920
pstSize->u32Height = 1080
pstSize->u32Width = 1920
pstSize->u32Height = 1080
[SAMPLE_COMM_VI_StartMIPI]-494: sensor 0 stDevAttr.devno 0
[sensor_prob = lt6911_probe]
###########   PinMux  #######################################################################
###########   PinMux End  #######################################################################
[lt6911_probe] -189
[lt6911_probe] -195
[lt6911_i2c_write] : addr = ee. data = 1
[lt6911_i2c_read] : addr = 0
[lt6911_i2c_write] : addr = ee. data = 0
[lt6911_i2c_write] : addr = ee. data = 1
[lt6911_i2c_read] : addr = 1
[lt6911_i2c_write] : addr = ee. data = 0
[lt6911_probe] jump return nVal -198
[lt6911_probe] -201
data:ffffffff ffffffff
[lt6911_probe] jump return CVI_FAILURE -206
[lt6911_probe] -208 = exit success
pstSize->u32Width = 1920
pstSize->u32Height = 1080
20250524 14:22:22.476 1789 E isp AE_InitSensorFpsPara:5555 pfn_cmos_fps_set NULL!

AE_SetExposure inttime update NULL.
awbInit ver 6.9@2021500
0 R:1400 B:3100 CT:2850
1 R:1500 B:2500 CT:3900
2 R:2300 B:1600 CT:6500
Golden 1024 1024 1024
WB Quadratic:0
isWdr:0
20250524 14:22:22.482 1789 E isp setNoiseProfile:3460 Noise profile get fail. Please check
********************************************************************************
cvi_bin_isp message
gerritId:      97347          commitId:      fc6ce647
md5:           d6db2297ddfd44e8252c1f3f888f47b2
sensorNum      1
sensorName0    6911

PQBIN message
gerritId:
              commitId:      fc6ce647
md5:           d6db2297ddfd44e8252c1f3f888f47b2
sensorNum      1
sensorName0    4653

author:        lxowalle       desc:          gc4653 30fps
createTime:    2024-03-26 13:41:34version:
tool Version:       v3.0.5.48           mode:
********************************************************************************
sensorName(0) mismatch, mwSns:6911 != pqBinSns:4653
[SAMPLE_COMM_ISP_Thread]-95: ISP Dev 0 running!
pstSize->u32Width = 1920
pstSize->u32Height = 1080
maix multi-media init ok
try release vio ok
try release venc ok
mmf_add_vi_channel..
2025/05/24 14:22:22 config loaded successfully
mmf_add_vi_channel..
mmf_add_vi_channel..
maix multi-media driver destroyed.
ISP Vipipe(0) Free pa(0x8bef4000) va(0x0x3fcdaaa000)
[SAMPLE_COMM_SNS_ParseIni]-2204: Parse /mnt/data/sensor_cfg.ini
[parse_source_devnum]-1797: devNum =  1
[parse_sensor_name]-1878: sensor =  LONTIUM_LT6911_2M_60FPS_8BIT
[parse_sensor_busid]-1907: bus_id =  4
[parse_sensor_i2caddr]-1918: sns_i2c_addr =  ff
[parse_sensor_mipidev]-1929: mipi_dev =  0
[parse_sensor_laneid]-1940: Lane_id =  2, 4, 3, 1, 0
[parse_sensor_pnswap]-1951: pn_swap =  0, 0, 0, 0, 0
[parse_sensor_mclken]-1973: mclk_en =  0
[parse_sensor_mclk]-1984: mclk =  0
try release sys ok
mmf insmod..
rmmod: can't unload module 'soph_vpss': Resource temporarily unavailable
insmod: can't insert '/mnt/system/ko/soph_base.ko': File exists
insmod: can't insert '/mnt/system/ko/soph_rtos_cmdqu.ko': File exists
insmod: can't insert '/mnt/system/ko/soph_fast_image.ko': File exists
insmod: can't insert '/mnt/system/ko/soph_mipi_rx.ko': File exists
insmod: can't insert '/mnt/system/ko/soph_snsr_i2c.ko': File exists
insmod: can't insert '/mnt/system/ko/soph_vi.ko': File exists
insmod: can't insert '/mnt/system/ko/soph_vpss.ko': File exists
[_mmf_init]-871: maix multi-media version:67a90e2-musl_riscv64
[SAMPLE_COMM_SNS_ParseIni]-2204: Parse /mnt/data/sensor_cfg.ini
[parse_source_devnum]-1797: devNum =  1
[parse_sensor_name]-1878: sensor =  LONTIUM_LT6911_2M_60FPS_8BIT
[parse_sensor_busid]-1907: bus_id =  4
[parse_sensor_i2caddr]-1918: sns_i2c_addr =  ff
[parse_sensor_mipidev]-1929: mipi_dev =  0
[parse_sensor_laneid]-1940: Lane_id =  2, 4, 3, 1, 0
[parse_sensor_pnswap]-1951: pn_swap =  0, 0, 0, 0, 0
[parse_sensor_mclken]-1973: mclk_en =  0
[parse_sensor_mclk]-1984: mclk =  0
pstSize->u32Width = 1920
pstSize->u32Height = 1080
[ION] 12533760  8b300000  VbPool0
pstSize->u32Width = 1920
pstSize->u32Height = 1080
pstSize->u32Width = 1920
pstSize->u32Height = 1080
ISP Vipipe(0) Allocate pa(0x8bef4000) va(0x0x3fcdaaa000) size(291424)
pstSize->u32Width = 1920
pstSize->u32Height = 1080
stSnsrMode.u16Width 1920 stSnsrMode.u16Height 1080 60.000000 wdrMode 0 pstSnsObj 0x3fce828e20
pstSize->u32Width = 1920
pstSize->u32Height = 1080
pstSize->u32Width = 1920
pstSize->u32Height = 1080
[SAMPLE_COMM_VI_StartMIPI]-494: sensor 0 stDevAttr.devno 0
[sensor_prob = lt6911_probe]
###########   PinMux  #######################################################################
###########   PinMux End  #######################################################################
[lt6911_probe] -189
[lt6911_probe] -195
[lt6911_i2c_write] : addr = ee. data = 1
[lt6911_i2c_read] : addr = 0
[lt6911_i2c_write] : addr = ee. data = 0
[lt6911_i2c_write] : addr = ee. data = 1
[lt6911_i2c_read] : addr = 1
[lt6911_i2c_write] : addr = ee. data = 0
[lt6911_probe] jump return nVal -198
[lt6911_probe] -201
data:ffffffff ffffffff
[lt6911_probe] jump return CVI_FAILURE -206
[lt6911_probe] -208 = exit success
pstSize->u32Width = 1920
pstSize->u32Height = 1080
20250524 14:22:23.525 1789 E isp AE_GetStatisticsConfig:4202 pstAeStatisticsCfg is NULL.
20250524 14:22:23.526 1789 E isp AE_SetStatisticsConfig:4188 pstAeStatisticsCfg is NULL.
20250524 14:22:23.526 1789 E isp AE_InitSensorFpsPara:5555 pfn_cmos_fps_set NULL!

AE_SetExposure inttime update NULL.
awbInit ver 6.9@2021500
0 R:1400 B:3100 CT:2850
1 R:1500 B:2500 CT:3900
2 R:2300 B:1600 CT:6500
Golden 1024 1024 1024
WB Quadratic:0
isWdr:0
20250524 14:22:23.533 1789 E isp setNoiseProfile:3460 Noise profile get fail. Please check
********************************************************************************
cvi_bin_isp message
gerritId:      97347          commitId:      fc6ce647
md5:           d6db2297ddfd44e8252c1f3f888f47b2
sensorNum      1
sensorName0    6911

PQBIN message
gerritId:
              commitId:      fc6ce647
md5:           d6db2297ddfd44e8252c1f3f888f47b2
sensorNum      1
sensorName0    4653

author:        lxowalle       desc:          gc4653 30fps
createTime:    2024-03-26 13:41:34version:
tool Version:       v3.0.5.48           mode:
********************************************************************************
sensorName(0) mismatch, mwSns:6911 != pqBinSns:4653
[SAMPLE_COMM_ISP_Thread]-95: ISP Dev 0 running!
pstSize->u32Width = 1920
pstSize->u32Height = 1080
maix multi-media init ok
try release vio ok
try release venc ok
mmf_add_vi_channel..

## /etc/init.d/S95nanokvm stop
killall: kvm_system: no process killed
killall: NanoKVM-Server: no process killed
rm: can't remove '/tmp/kvm_system': No such file or directory
rm: can't remove '/tmp/server': No such file or directory
OK
# /etc/init.d/S95nanokvm start
beta
# [SAMPLE_COMM_SNS_ParseIni]-2204: Parse /mnt/data/sensor_cfg.ini
[parse_source_devnum]-1797: devNum =  1
[parse_sensor_name]-1878: sensor =  LONTIUM_LT6911_2M_60FPS_8BIT
[parse_sensor_busid]-1907: bus_id =  4
[parse_sensor_i2caddr]-1918: sns_i2c_addr =  ff
[parse_sensor_mipidev]-1929: mipi_dev =  0
[parse_sensor_laneid]-1940: Lane_id =  2, 4, 3, 1, 0
[parse_sensor_pnswap]-1951: pn_swap =  0, 0, 0, 0, 0
[parse_sensor_mclken]-1973: mclk_en =  0
[parse_sensor_mclk]-1984: mclk =  0
try release sys ok
mmf insmod..
rmmod: can't unload module 'soph_vpss': Resource temporarily unavailable
insmod: can't insert '/mnt/system/ko/soph_base.ko': File exists
insmod: can't insert '/mnt/system/ko/soph_rtos_cmdqu.ko': File exists
-- [E] write failed
oled not exist
insmod: can't insert '/mnt/system/ko/soph_fast_image.ko': File exists
rm: can't remove '/etc/kvm/oled_exist': No such file or directory
insmod: can't insert '/mnt/system/ko/soph_mipi_rx.ko': File exists
insmod: can't insert '/mnt/system/ko/soph_snsr_i2c.ko': File exists
192.168.1.105
insmod: can't insert '/mnt/system/ko/soph_vi.ko': File exists
rm: can't remove '/etc/kvm/wifi_exist': No such file or directory
insmod: can't insert '/mnt/system/ko/soph_vpss.ko': File exists
[_mmf_init]-871: maix multi-media version:67a90e2-musl_riscv64
[SAMPLE_COMM_SNS_ParseIni]-2204: Parse /mnt/data/sensor_cfg.ini
[parse_source_devnum]-1797: devNum =  1
[parse_sensor_name]-1878: sensor =  LONTIUM_LT6911_2M_60FPS_8BIT
[parse_sensor_busid]-1907: bus_id =  4
[parse_sensor_i2caddr]-1918: sns_i2c_addr =  ff
[parse_sensor_mipidev]-1929: mipi_dev =  0
[parse_sensor_laneid]-1940: Lane_id =  2, 4, 3, 1, 0
[parse_sensor_pnswap]-1951: pn_swap =  0, 0, 0, 0, 0
[parse_sensor_mclken]-1973: mclk_en =  0
[parse_sensor_mclk]-1984: mclk =  0
pstSize->u32Width = 1920
pstSize->u32Height = 1080
[ION] 12533760  8b300000  VbPool0
[ION] 294912  8bef4000  ISP_SHARED_BUFFER_0
alloc_buf_size(294912): 294912, phy_addr(8bef4000): 0x8bef4000, buffer_name: ISP_SHARED_BUFFER_0
ion_data.size:294912, ion_data.addr_p:0x8bef4000, ion_data.name:ISP_SHARED_BUFFER_0
pstSize->u32Width = 1920
pstSize->u32Height = 1080
pstSize->u32Width = 1920
pstSize->u32Height = 1080
ISP Vipipe(0) Allocate pa(0x8bef4000) va(0x0x3fcdaaa000) size(291424)
pstSize->u32Width = 1920
pstSize->u32Height = 1080
stSnsrMode.u16Width 1920 stSnsrMode.u16Height 1080 60.000000 wdrMode 0 pstSnsObj 0x3fce828e20
pstSize->u32Width = 1920
pstSize->u32Height = 1080
pstSize->u32Width = 1920
pstSize->u32Height = 1080
[SAMPLE_COMM_VI_StartMIPI]-494: sensor 0 stDevAttr.devno 0
[sensor_prob = lt6911_probe]
###########   PinMux  #######################################################################
###########   PinMux End  #######################################################################
[lt6911_probe] -189
[lt6911_probe] -195
[lt6911_i2c_write] : addr = ee. data = 1
[lt6911_i2c_read] : addr = 0
[lt6911_i2c_write] : addr = ee. data = 0
[lt6911_i2c_write] : addr = ee. data = 1
[lt6911_i2c_read] : addr = 1
[lt6911_i2c_write] : addr = ee. data = 0
[lt6911_probe] jump return nVal -198
[lt6911_probe] -201
data:ffffffff ffffffff
[lt6911_probe] jump return CVI_FAILURE -206
[lt6911_probe] -208 = exit success
pstSize->u32Width = 1920
pstSize->u32Height = 1080
20250524 14:22:22.476 1789 E isp AE_InitSensorFpsPara:5555 pfn_cmos_fps_set NULL!

AE_SetExposure inttime update NULL.
awbInit ver 6.9@2021500
0 R:1400 B:3100 CT:2850
1 R:1500 B:2500 CT:3900
2 R:2300 B:1600 CT:6500
Golden 1024 1024 1024
WB Quadratic:0
isWdr:0
20250524 14:22:22.482 1789 E isp setNoiseProfile:3460 Noise profile get fail. Please check
********************************************************************************
cvi_bin_isp message
gerritId:      97347          commitId:      fc6ce647
md5:           d6db2297ddfd44e8252c1f3f888f47b2
sensorNum      1
sensorName0    6911

PQBIN message
gerritId:
              commitId:      fc6ce647
md5:           d6db2297ddfd44e8252c1f3f888f47b2
sensorNum      1
sensorName0    4653

author:        lxowalle       desc:          gc4653 30fps
createTime:    2024-03-26 13:41:34version:
tool Version:       v3.0.5.48           mode:
********************************************************************************
sensorName(0) mismatch, mwSns:6911 != pqBinSns:4653
[SAMPLE_COMM_ISP_Thread]-95: ISP Dev 0 running!
pstSize->u32Width = 1920
pstSize->u32Height = 1080
maix multi-media init ok
try release vio ok
try release venc ok
mmf_add_vi_channel..
2025/05/24 14:22:22 config loaded successfully
mmf_add_vi_channel..
mmf_add_vi_channel..
maix multi-media driver destroyed.
ISP Vipipe(0) Free pa(0x8bef4000) va(0x0x3fcdaaa000)
[SAMPLE_COMM_SNS_ParseIni]-2204: Parse /mnt/data/sensor_cfg.ini
[parse_source_devnum]-1797: devNum =  1
[parse_sensor_name]-1878: sensor =  LONTIUM_LT6911_2M_60FPS_8BIT
[parse_sensor_busid]-1907: bus_id =  4
[parse_sensor_i2caddr]-1918: sns_i2c_addr =  ff
[parse_sensor_mipidev]-1929: mipi_dev =  0
[parse_sensor_laneid]-1940: Lane_id =  2, 4, 3, 1, 0
[parse_sensor_pnswap]-1951: pn_swap =  0, 0, 0, 0, 0
[parse_sensor_mclken]-1973: mclk_en =  0
[parse_sensor_mclk]-1984: mclk =  0
try release sys ok
mmf insmod..
rmmod: can't unload module 'soph_vpss': Resource temporarily unavailable
insmod: can't insert '/mnt/system/ko/soph_base.ko': File exists
insmod: can't insert '/mnt/system/ko/soph_rtos_cmdqu.ko': File exists
insmod: can't insert '/mnt/system/ko/soph_fast_image.ko': File exists
insmod: can't insert '/mnt/system/ko/soph_mipi_rx.ko': File exists
insmod: can't insert '/mnt/system/ko/soph_snsr_i2c.ko': File exists
insmod: can't insert '/mnt/system/ko/soph_vi.ko': File exists
insmod: can't insert '/mnt/system/ko/soph_vpss.ko': File exists
[_mmf_init]-871: maix multi-media version:67a90e2-musl_riscv64
[SAMPLE_COMM_SNS_ParseIni]-2204: Parse /mnt/data/sensor_cfg.ini
[parse_source_devnum]-1797: devNum =  1
[parse_sensor_name]-1878: sensor =  LONTIUM_LT6911_2M_60FPS_8BIT
[parse_sensor_busid]-1907: bus_id =  4
[parse_sensor_i2caddr]-1918: sns_i2c_addr =  ff
[parse_sensor_mipidev]-1929: mipi_dev =  0
[parse_sensor_laneid]-1940: Lane_id =  2, 4, 3, 1, 0
[parse_sensor_pnswap]-1951: pn_swap =  0, 0, 0, 0, 0
[parse_sensor_mclken]-1973: mclk_en =  0
[parse_sensor_mclk]-1984: mclk =  0
pstSize->u32Width = 1920
pstSize->u32Height = 1080
[ION] 12533760  8b300000  VbPool0
pstSize->u32Width = 1920
pstSize->u32Height = 1080
pstSize->u32Width = 1920
pstSize->u32Height = 1080
ISP Vipipe(0) Allocate pa(0x8bef4000) va(0x0x3fcdaaa000) size(291424)
pstSize->u32Width = 1920
pstSize->u32Height = 1080
stSnsrMode.u16Width 1920 stSnsrMode.u16Height 1080 60.000000 wdrMode 0 pstSnsObj 0x3fce828e20
pstSize->u32Width = 1920
pstSize->u32Height = 1080
pstSize->u32Width = 1920
pstSize->u32Height = 1080
[SAMPLE_COMM_VI_StartMIPI]-494: sensor 0 stDevAttr.devno 0
[sensor_prob = lt6911_probe]
###########   PinMux  #######################################################################
###########   PinMux End  #######################################################################
[lt6911_probe] -189
[lt6911_probe] -195
[lt6911_i2c_write] : addr = ee. data = 1
[lt6911_i2c_read] : addr = 0
[lt6911_i2c_write] : addr = ee. data = 0
[lt6911_i2c_write] : addr = ee. data = 1
[lt6911_i2c_read] : addr = 1
[lt6911_i2c_write] : addr = ee. data = 0
[lt6911_probe] jump return nVal -198
[lt6911_probe] -201
data:ffffffff ffffffff
[lt6911_probe] jump return CVI_FAILURE -206
[lt6911_probe] -208 = exit success
pstSize->u32Width = 1920
pstSize->u32Height = 1080
20250524 14:22:23.525 1789 E isp AE_GetStatisticsConfig:4202 pstAeStatisticsCfg is NULL.
20250524 14:22:23.526 1789 E isp AE_SetStatisticsConfig:4188 pstAeStatisticsCfg is NULL.
20250524 14:22:23.526 1789 E isp AE_InitSensorFpsPara:5555 pfn_cmos_fps_set NULL!

AE_SetExposure inttime update NULL.
awbInit ver 6.9@2021500
0 R:1400 B:3100 CT:2850
1 R:1500 B:2500 CT:3900
2 R:2300 B:1600 CT:6500
Golden 1024 1024 1024
WB Quadratic:0
isWdr:0
20250524 14:22:23.533 1789 E isp setNoiseProfile:3460 Noise profile get fail. Please check
********************************************************************************
cvi_bin_isp message
gerritId:      97347          commitId:      fc6ce647
md5:           d6db2297ddfd44e8252c1f3f888f47b2
sensorNum      1
sensorName0    6911

PQBIN message
gerritId:
              commitId:      fc6ce647
md5:           d6db2297ddfd44e8252c1f3f888f47b2
sensorNum      1
sensorName0    4653

author:        lxowalle       desc:          gc4653 30fps
createTime:    2024-03-26 13:41:34version:
tool Version:       v3.0.5.48           mode:
********************************************************************************
sensorName(0) mismatch, mwSns:6911 != pqBinSns:4653
[SAMPLE_COMM_ISP_Thread]-95: ISP Dev 0 running!
pstSize->u32Width = 1920
pstSize->u32Height = 1080
maix multi-media init ok
try release vio ok
try release venc ok
mmf_add_vi_channel..

#
```
